default: &default
  adapter: postgresql
  encoding: unicode
  username: <uname>
  password: <password>
  host: localhost
  pool: 5

development:
  <<: *default
  database: url_shortner_development

test:
  <<: *default
  database: url_shortner_test

production:
  <<: *default
  database: url_shortner_production
